# Mastering Masking & Data Clearning With Numpy (gfg)

In [2]:
import numpy as np

### 1. Masking With Boolean Array

In [3]:
arr = np.array([1,2,np.nan,np.nan,5,6])
print(np.isnan(arr)) 
print(~np.isnan(arr)) # using ~ will mask the true to false and false to true , or simpley inverse. 

print(arr[np.isnan(arr)]) # using this will help us to print only the nan values 
print(arr[~np.isnan(arr)]) # using this will help us to print only the non-nan values 


[False False  True  True False False]
[ True  True False False  True  True]
[nan nan]
[1. 2. 5. 6.]


### 2. Replacing outliers with s specific values 

In [4]:
array = np.array([1,2,3,4,5,6,7,8,9])
array[array>7] = 1000
array[array<2] = 200
array

array([ 200,    2,    3,    4,    5,    6,    7, 1000, 1000])

### 3. Removing The Duplicate

In [5]:
Uarr = np.array([1,2,3,3,3,4,4,5,6,6,7,7,8,8])
unique_arr = np.unique(Uarr)
print(unique_arr) # we can sue np.unique for removing the duplicate 
print(set(Uarr)) # we can also use the set data strture for that.


[1 2 3 4 5 6 7 8]
{np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8)}


### 4. Categorical Data to One Hot Encoding

In [7]:
categorial_arr = np.array(['A','B','C','D','E'])
print(categorial_arr)
num_arr = [0,1,2,3,4]
one_hot_arr = np.eye(5)[num_arr]
one_hot_arr

['A' 'B' 'C' 'D' 'E']


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 5. Data Normalization

In [8]:
## Salary May range (10000 - 10000000)
## Age may range (18-90)
## WOrd_ex may range (0 - 60)

# as we can see these all are different numbers and ranges , so we have to normalize it and get in a range which is same for all 
## here we are using min max normalization 

salary = np.array([10000,10000000,45666,76776,8769679,4354523])
normalize_salary =( salary - salary.min() )/(salary.max() - salary.min() )
print(normalize_salary)



[0.         1.         0.00357017 0.00668428 0.87684474 0.43488719]
